version: "2"

services:
  conda-store-build:
    build: .
    volumes:
      - ./tests/assets/environments:/opt/environments:ro
      - ./data/conda-store:/data
    command: ['python', '-m', 'conda_store', 'build', '-p', '/opt/environments', '-e', '/data/envs', '-s', '/data/store', '--uid', '1000', '--gid', '100', '--permissions', '775', '--storage-backend', 's3']
    environment:
      TZ: America/New_York
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: admin
      S3_SECRET_KEY: password
      PATH: "/opt/conda/envs/conda-store/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  conda-store-ui:
    build: .
    volumes:
      - ./data/conda-store:/data
    command: ['python', '-m', 'conda_store', 'serve', '-s', '/data/store', '--port', '5000']
    ports:
      - "5000:5000"
    environment:
      TZ: America/New_York
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: admin
      S3_SECRET_KEY: password
      PATH: "/opt/conda/envs/conda-store/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  minio:
    image: minio/minio:RELEASE.2020-11-10T21-02-24Z
    ports:
      - "9000:9000"
    command: "server /data"
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
