version: "2"

services:
  conda-store-worker:
    build: conda-store-server
    depends_on:
      - "postgres"
      - "minio"
    volumes:
      - ./tests/assets/environments:/opt/environments:ro
      - ./tests/assets/conda_store_config.py:/opt/conda_store/conda_store_config.py:ro
    platform: linux/amd64
    command: ["wait-for-it", "conda-store-server:5000", "-t", "60", '--', 'conda-store-worker', '--config', '/opt/conda_store/conda_store_config.py']

  conda-store-server:
    build: conda-store-server
    depends_on:
      - "postgres"
      - "minio"
    volumes:
      - ./tests/assets/conda_store_config.py:/opt/conda_store/conda_store_config.py:ro
    platform: linux/amd64
    command: ["wait-for-it", "postgres:5432", '--', 'conda-store-server', '--config', '/opt/conda_store/conda_store_config.py']
    # command: ["wait-for-it", "mysql:3306", '--', 'conda-store-server', '--config', '/opt/conda_store/conda_store_config.py']
    ports:
      - "5000:5000"

  jupyterhub:
    build: conda-store
    user: "1000:1000"
    volumes:
      - ./tests/assets/jupyter_notebook_config.py:/etc/jupyter/jupyter_notebook_config.py
      - ./tests/assets/jupyterhub_config.py:/opt/jupyterhub/jupyterhub_config.py:ro
    platform: linux/amd64
    command: ['/opt/conda/envs/conda-store/bin/jupyterhub', '--config', '/opt/jupyterhub/jupyterhub_config.py']
    ports:
      - "8000:8000"

  minio:
    image: minio/minio:RELEASE.2020-11-10T21-02-24Z
    ports:
      - "9000:9000"
    entrypoint: sh
    command: -c 'mkdir -p /data/conda-store && /usr/bin/minio server /data'
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password

  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conda-store

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: hbgY8bkoWPMM7EjtcD6wrlVX
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: conda-store
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
