version: "3"

services:
  conda-store-build:
    build: .
    volumes:
      - ./tests/assets/environments:/opt/environments:ro
      - /tmp/conda-store/mount:/opt/mount
    command: ['python', '-m', 'conda_store', 'build', '-p', '/opt/environments', '-o', '/opt/mount/environments', '-s', '/opt/mount/store', '--uid', '1000', '--gid', '100', '--permissions', '775']
    environment:
      TZ: America/New_York
      PATH: "/opt/conda/envs/conda-store/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  conda-store-ui:
    build: .
    volumes:
      - /tmp/conda-store/mount:/opt/mount
    command: ['python', '-m', 'conda_store', 'ui', '-s', '/opt/mount/store', '--port', '5000']
    ports:
      - "5000:5000"
    environment:
      TZ: America/New_York
      PATH: "/opt/conda/envs/conda-store/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  conda-store-api:
    build: .
    volumes:
      - /tmp/conda-store/mount:/opt/mount
    command: ['python', '-m', 'conda_store', 'api', '-s', '/opt/mount/store', '--port', '5001']
    ports:
      - "5001:5001"
    environment:
      TZ: America/New_York
      PATH: "/opt/conda/envs/conda-store/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  conda-store-registry:
    build: .
    volumes:
      - /tmp/conda-store:/opt/mount
    command: ['python', '-m', 'conda_store', 'registry', '-s', '/opt/mount/store', '--port', '5002']
    ports:
      - "5002:5002"
    environment:
      TZ: America/New_York
      PATH: "/opt/conda/envs/conda-store/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
