name: "Build Docker Images"

on:
  push:
    branches:
      - master

jobs:
  build:
    name: 'Build Docker Image'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Infrastructure'
        uses: actions/checkout@master
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Docker Build, Tag, Push Image
        env:
          IMAGE_NAME: quansight/conda-store
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
      - name: Docker Logout
        run: |
          docker logout
