name: Build and publish Helm chart

on:
  push:
    tags: ["**"]

  workflow_dispatch:

jobs:
  build-publish-helm-chart:
    name: Build and publish Helm chart
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install chart publishing dependencies
        run: |
          pip install chartpress pyyaml
          pip list
          helm version

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure a git user
        run: |
          git config --global user.email "github-actions@example.local"
          git config --global user.name "GitHub Actions user"

      - name: Build and publish Helm chart with chartpress
        env:
          GITHUB_ACTOR: ""
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: resources/helm/tools/build-publish-helm-chart.sh
